name: Content-Grep 2 Testing

on:
  workflow_dispatch:
  push:
    paths:
      - "cgrep/**/**.go"

env:
  TARGET: cgrep-2
  APP: cgrep

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - id: result
        name: Go Test
        working-directory: ./${{ env.APP }}
        run: |
          go test -v -timeout 15s -run TestRenderFiles ./result/...
          go test -v -timeout 15s -run TestRenderWithContent ./result/...
          go test -v -timeout 15s ./cmd/...
