name: Content-Grep 2 Testing

on:
  workflow_dispatch:
  push:
    paths:
      - "cgrep/**/**.go"

env:
  TARGET: cgrep-2
  APP: cgrep

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - id: result
        name: Go Test
        working-directory: ./${{ env.APP }}
        run: |
          go test -v -run TestRenderFiles ./result/...
          go test -v -run TestRenderWithContent ./result/...
          go test -v ./cmd/...

      - name: Send result
        if: always()
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"account" : "${{ github.actor }}" , "chapter" : "${{ env.TARGET }}", "result": "${{ steps.result.conclusion }}"}' \
            ${{ secrets.RESULT_API }}
