name: murl 1 Testing

on:
  workflow_dispatch:
  push:
    paths:
      - "murl/**/**.go"

env:
  TARGET: murl-1
  APP: murl

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - id: result
        name: Go Test
        working-directory: ./${{ env.APP }}
        run: |
          go test -v -run NewHttpClient ./client/...
